photos/urls.py
from django.urls import path

from . import views

app_name = 'photos'

urlpatterns = [
    # /photos/
    path('', views.AllPosts.as_view(), name='index'),

    # /photos/like-actions/34/
    path('like-actions/<int:post_pk>/', views.like_or_unlike, name='liker'),

    # /photos/upload/
    path('upload/', views.UploadImage.as_view(), name='upload'),

    # photos/api/index/
    path('api/index/', views.all_posts_api, name='api_index'),

    # photos/api/upload/
    path('api/upload/', views.upload_image_api, name='api_upload'),
]

s3photos/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static, serve

from .views import photos_open, photos_ng, NgAssets

urlpatterns = [
    path('admin/', admin.site.urls),

    path('photos/', include('photos.urls')),

    path('', RedirectView.as_view(url='/photos/')),

    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL+"favicon.ico")),

    # media  | comment out when debug is true
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    # static  | comment out when debug is true
    re_path('^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    # /open/*
    re_path(r'open/(?P<path>.*)', photos_open, name='open'),

    # ng assets redirect
    re_path(r'ng/assets/(?P<path>.*)', NgAssets.as_view()),

    # /ng/*
    re_path(r'ng(?P<path>.*)', photos_ng, name='ng'),

]

photos/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    uploaded_by = models.CharField(max_length=400)
    image_file = models.ImageField(verbose_name='Pic', upload_to='photos/')
    caption = models.CharField(max_length=300)
    likes = models.IntegerField(default=0)
    time = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return "Post by {}".format(self.uploaded_by)

    def get_clean_time(self):
        return self.time.strftime("%B %d, %Y, %I:%M %p")

    def liking_url(self):
        return reverse('photos:liker', args=[str(self.pk)])

    def delete(self, *args, **kwargs):
        self.image_file.delete()
        return super().delete()

photos/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.validators import ValidationError

from .models import Post


class PostForm(forms.Form):
    file = forms.ImageField(help_text='Choose an image', widget=forms.FileInput(attrs={'class': 'form-control'}))
    caption = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        max_length=200,
        help_text='Tell others what the image is about'
    )
    your_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=400,
        help_text='Enter a name you would like to be known as'
    )

    def clean_your_name(self):
        data = self.cleaned_data['your_name']
        if len(data) < 2:
            raise ValidationError(_("A valid name needs be longer than '{}'".format(str(data))))
        return data

    def clean_caption(self):
        data = self.cleaned_data['caption']
        if not data:
            raise ValidationError(_('We think you image needs a caption to say what it\'s about.'))
        return data

    def save(self):
        data = self.cleaned_data
        new_post = Post(
            uploaded_by=data['your_name'],
            image_file=data['file'],
            caption=data['caption']
        )
        new_post.save()
        return new_post

photos/views.py
from django.views.generic import ListView, FormView
from django.http import JsonResponse, Http404, HttpResponse
from django.shortcuts import get_object_or_404, reverse
from django.views.decorators.csrf import ensure_csrf_cookie

from .models import Post
from .forms import PostForm
from .serializers import PostSerializer


class AllPosts(ListView):
    model = Post
    template_name = 'photos/post_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        query = self.request.GET.get('post-query', '')
        context = super().get_context_data()

        if query and 'object_list' in context:
            context['object_list'] = context['object_list'].filter(uploaded_by__icontains=query)

        context.update({
            'liked': self.request.session.setdefault('liked', []),
            'post_query': query
        })

        return context


class UploadImage(FormView):
    template_name = 'photos/upload.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('photos:index')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def like_or_unlike(request, post_pk):
    liked_posts = list(request.session.setdefault('liked', []))

    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_pk)
        liked = False

        if post_pk in liked_posts:
            post.likes -= 1
            liked_posts.remove(post_pk)
        else:
            post.likes += 1
            liked_posts.append(post_pk)
            liked = True

        post.save()
        request.session['liked'] = liked_posts

        return JsonResponse({
            'liked': liked,
            'likes': post.likes
        })

    else:
        raise Http404


@ensure_csrf_cookie
def all_posts_api(request):
    posts = Post.objects.all()

    query = request.GET.get('post-query', None)

    if query:
        posts = posts.filter(uploaded_by__icontains=query)

    return JsonResponse(
        data={
            'posts': PostSerializer(posts, many=True).data,
            'liked': request.session.setdefault('liked', [])
        },
        safe=False
    )


def upload_image_api(request):
    if request.method == 'GET':
        form = PostForm()
        fields = {field: form.fields[field].help_text for field in form.fields}
        return JsonResponse({
            'fields': fields
        })

    elif request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        status_code = 201

        if form.is_valid():
            post = form.save()
            response = {
                'success': True,
                'post': PostSerializer(post).data
            }

        else:
            status_code = 400
            response = {
                'success': False,
                'errors': form.errors
            }

        return JsonResponse(response, status=status_code)

    return HttpResponse(":-(", status=405)

s3photos/views.py
from django.views.generic import RedirectView
from django.conf import settings
from django.shortcuts import render


def photos_open(request, **kwargs):
    return render(request, 'open/index.html')


def photos_ng(request, **kwargs):
    return render(request, 'ng/index.html')


class NgAssets(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('path'):
            return f'{settings.STATIC_URL}ng/assets/{kwargs.get("path")}'

        return super().get_redirect_url(*args, **kwargs)

photos/templates/ng/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <meta charset="utf-8">
    <title>S3photos</title>
    <base href="/ng/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @font-face {
            font-family: 'Oregano';
            font-style: italic;
            font-weight: 400;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/oregano/v13/If2KXTPxciS3H4S2oZXlMhHK7SDvqtws.woff2) format('woff2');
            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
        }

        @font-face {
            font-family: 'Oregano';
            font-style: italic;
            font-weight: 400;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/oregano/v13/If2KXTPxciS3H4S2oZXlPBHK7SDvqg.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }
    </style>

    <style>
        @charset "UTF-8";
        :root {
            --bs-blue: #0d6efd;
            --bs-indigo: #6610f2;
            --bs-purple: #6f42c1;
            --bs-pink: #d63384;
            --bs-red: #dc3545;
            --bs-orange: #fd7e14;
            --bs-yellow: #ffc107;
            --bs-green: #198754;
            --bs-teal: #20c997;
            --bs-cyan: #0dcaf0;
            --bs-black: #000;
            --bs-white: #fff;
            --bs-gray: #6c757d;
            --bs-gray-dark: #343a40;
            --bs-gray-100: #f8f9fa;
            --bs-gray-200: #e9ecef;
            --bs-gray-300: #dee2e6;
            --bs-gray-400: #ced4da;
            --bs-gray-500: #adb5bd;
            --bs-gray-600: #6c757d;
            --bs-gray-700: #495057;
            --bs-gray-800: #343a40;
            --bs-gray-900: #212529;
            --bs-primary: #0d6efd;
            --bs-secondary: #6c757d;
            --bs-success: #198754;
            --bs-info: #0dcaf0;
            --bs-warning: #ffc107;
            --bs-danger: #dc3545;
            --bs-light: #f8f9fa;
            --bs-dark: #212529;
            --bs-primary-rgb: 13, 110, 253;
            --bs-secondary-rgb: 108, 117, 125;
            --bs-success-rgb: 25, 135, 84;
            --bs-info-rgb: 13, 202, 240;
            --bs-warning-rgb: 255, 193, 7;
            --bs-danger-rgb: 220, 53, 69;
            --bs-light-rgb: 248, 249, 250;
            --bs-dark-rgb: 33, 37, 41;
            --bs-white-rgb: 255, 255, 255;
            --bs-black-rgb: 0, 0, 0;
            --bs-body-color-rgb: 33, 37, 41;
            --bs-body-bg-rgb: 255, 255, 255;
            --bs-font-sans-serif: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
            --bs-font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
            --bs-gradient: linear-gradient(180deg, rgba(255, 255, 255, .15), rgba(255, 255, 255, 0));
            --bs-body-font-family: var(--bs-font-sans-serif);
            --bs-body-font-size: 1rem;
            --bs-body-font-weight: 400;
            --bs-body-line-height: 1.5;
            --bs-body-color: #212529;
            --bs-body-bg: #fff;
            --bs-border-width: 1px;
            --bs-border-style: solid;
            --bs-border-color: #dee2e6;
            --bs-border-color-translucent: rgba(0, 0, 0, .175);
            --bs-border-radius: .375rem;
            --bs-border-radius-sm: .25rem;
            --bs-border-radius-lg: .5rem;
            --bs-border-radius-xl: 1rem;
            --bs-border-radius-2xl: 2rem;
            --bs-border-radius-pill: 50rem;
            --bs-link-color: #0d6efd;
            --bs-link-hover-color: #0a58ca;
            --bs-code-color: #d63384;
            --bs-highlight-bg: #fff3cd
        }

        *, *:before, *:after {
            box-sizing: border-box
        }

        @media (prefers-reduced-motion: no-preference) {
            :root {
                scroll-behavior: smooth
            }
        }

        body {
            margin: 0;
            font-family: var(--bs-body-font-family);
            font-size: var(--bs-body-font-size);
            font-weight: var(--bs-body-font-weight);
            line-height: var(--bs-body-line-height);
            color: var(--bs-body-color);
            text-align: var(--bs-body-text-align);
            background-color: var(--bs-body-bg);
            -webkit-text-size-adjust: 100%;
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
        }

        html {
            font-size: 12px
        }
    </style>
    <link rel="stylesheet" href="{% static 'ng/css/styles.2b90713f35b7f41c.css' %}" media="print" onload="this.media='all'">
    <noscript>
        <link rel="stylesheet" href="{% static 'ng/css/styles.2b90713f35b7f41c.css' %}">
    </noscript>
</head>
<body>
    <app-root></app-root>
    <script src="{% static 'ng/js/runtime.d046f78174a81c17.js' %}" type="module"></script>
    <script src="{% static 'ng/js/polyfills.7ac548f6e657026e.js' %}" type="module"></script>
    <script src="{% static 'ng/js/main.64f68a8b1ff0f973.js' %}" type="module"></script>
</body>
</html>

photos/templates/open/index.html
{% load static %}<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/open/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="s3 photos app"/><link href="https://fonts.googleapis.com/css2?family=Oregano:ital@1&amp;display=swap" rel="stylesheet"><title>S3photos</title><script defer="defer" src="{% static 'open/js/main.af27edad.js' %}" ></script><link href="{% static 'open/css/main.b515e8d3.css' %}" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root" data-load-posts="/photos/api/index/" data-upload-post="/photos/api/upload/" data-token="{{ csrf_token }}" data-user-icon="{% static 'open/media/user.7e6384c0.svg' %}" data-time-icon="{% static 'open/media/clock.91acf993.svg' %}" data-heart-icon="{% static 'open/media/heart.c0a3b5af.svg' %}" data-heart-full-icon="{% static 'open/media/heart_full.1428a519.svg' %}"></div></body></html>

photos/templates/photos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>S3photos | {% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Oregano:ital@1&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}" />
    {% block style %}{% endblock style %}
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">S3photos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
          
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% block home %}{% endblock home %}" href="{% url 'photos:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block your %}{% endblock your %}" href="{% url 'photos:upload' %}">Upload</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/open/">open</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ng">ng</a>
                </li>
            </ul>
          <form method="GET" action="{% url 'photos:index' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="post-query" value="{{ post_query }}" placeholder="Search for posts, uploader and tags" aria-label="Search" required >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>

    <div class="main">
        {% block content %}
        {% endblock content %}
    </div>


    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock script %}
</body>
</html>

photos/templates/photos/post_list.html
{% extends "photos/base.html" %}
{% load static %}

{% block title %}all posts{% endblock title %}
{% block style %}<link rel="stylesheet" type="text/css" media="screen" href="{% static 'photos/css/post_list.css' %}" />{% endblock style %}
{% block home %}active{% endblock home %}

{% block content %}
    <div class="every">

        {% if object_list %}
            {% for post in object_list %}
            <div class="post card post-{{post.pk}}">
                <img src="{{post.image_file.url}}" alt="" class="post-img">
                <div class="post-info">
                    <!-- user and time info -->
                    <div class="info-post">
                        <div class="uploader">
                            <span class="uploader-info">
                                <img class="user-vector vector" src="{% static 'svg/user.svg' %}" alt="user-vector">
                                <a href="?post-query={{post.uploaded_by}}" class="uploader-name">{{post.uploaded_by}}</a>
                            </span>
                        </div>
                        <div class="date">
                            <img src="{% static 'svg/clock.svg' %}" alt="clock-vector" class="clock-vector vector">
                            <span class="posted-time">{{ post.time }}</span>
                        </div>
                    </div>

                    <!-- Caption -->
                    <div class="caption">
                        <p>{{ post.caption }}</p>
                    </div>

                    <!-- like button -->
                    <div class="like">
                        {% csrf_token %}
                        <img src="{% if post.pk in liked %}{% static 'svg/heart_full.svg' %}{% else %}{% static 'svg/heart.svg' %}{% endif %}" alt="like vector" class="vector liking" data-like-url="{{post.liking_url}}">
                        <span class="h-m-l" name='count'>{{post.likes}}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="container" id="no-posts">
                <div class="text-center">
                    <h2>
                        No posts availble at this moment
                        {% if post_query %}
                            for '{{ post_query }}'
                        {% endif %}

                    </h2>
                    <a href="{% url 'photos:upload' %}" class="btn btn-dark upload-btn">Upload to <span class="s3">S3photos</span></a>
                </div>
            </div>
        {% endif %}


    </div>


{% endblock content %}

{% block script %} <script src="{% static 'photos/js/post.js' %}"></script> {% endblock script %}

photos/templates/photos/upload.html
{% extends "photos/base.html" %}
{% load static %}

{% block title %}upload{% endblock title %}

{% block style %}<link rel="stylesheet" href="{% static 'photos/css/upload.css' %}" rel="stylesheet">{% endblock style %}

{% block your %}active{% endblock your %}

{% block content %}

<div class="cloud">
    
    <form id="form-upload" action="" method="POST" role="form" enctype="multipart/form-data">
        <legend class="text-center legend-form">Upload an image to <span class="s3">S3photos</span></legend>
        {% csrf_token %}

        {% if form.errors %}
            
            <div class="alert alert-warning text-center error">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                Please correct the errors below
            </div>
            
        {% endif %}

        <div class="img-to-up">
            <h6 class="text-center">You are about to upload the image below</h6>
            <img id="image-to-call" src="" alt="image to be uploaded">
        </div>

        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}                
                <div class="alert alert-warning {{field.label}}-alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ error }}
                </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-info {{field.label}}-alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{field.help_text}}
                </div>                
            {% endif %}

            <div class="form-group">
                <label for="">{{field.label}}</label>
                {{field}}
            </div>
            <hr>
        {% endfor %}
    
        
    
        <button type="submit" class="btn btn-dark upload-btn">Upload to <span class="s3">S3photos</span></button>
    </form>
</div>

{% endblock content %}

{% block script %}<script src="{% static 'photos/js/upload.js' %}"></script>{% endblock script %}